# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa952291ca6b8bdcea01937abc2f8289d25aa19653ee467ad57b718482370a599d39e75a87835751d07ae49183fe03d753b6e0e205bc5dcd72179a6da8f2c0a5

test:
  secret_key_base: 8afc9cdd9d998531ba1ef74255b771dc80c3d9a077fdd2719f97dfddf4c49972968f63be2e0bed6112c61f4325cb749ba7e9987504da4185cca9422a9d0dc893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
